package clases;

import actividad_5_1.actividad_5_1;
import java.awt.Color;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.*;
import javax.xml.transform.*;
import javax.xml.stream.*;
import javax.swing.JOptionPane;
import org.json.simple.*;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Result;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import javax.xml.transform.Result;
import javax.xml.transform.Source;
import org.w3c.dom.DOMImplementation;

public class FormCapturaPersonas extends javax.swing.JPanel {
    JSONArray jsonArray = new JSONArray();
    GeneradorXML generador = new GeneradorXML();
    ArrayList listaPersonas = new ArrayList<Persona>();
    ArrayList listaPersonas2 = new ArrayList<Persona>();
    TablaModeloPersona modeloDatosPersona = new TablaModeloPersona(listaPersonas);
    Boolean editando = false;
    int filaSeleccionada;
    /**
     * Creates new form FormCapturaPersonas
     */
    public FormCapturaPersonas() throws Exception{
       
        initComponents();
        this.setVisible(false);
        this.jTable1.setModel(modeloDatosPersona);
        // Llamar a los métodos necesarios
    }

    public static void imprimirValor(String valor) {
        JOptionPane.showMessageDialog(null, valor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        choice1 = new java.awt.Choice();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        form_Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        form_dni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        form_nombre = new javax.swing.JTextField();
        form_ape1 = new javax.swing.JTextField();
        form_ape2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        form_fechaNac = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        form_email = new javax.swing.JTextField();
        form_pwd = new javax.swing.JPasswordField();
        jToolBar2 = new javax.swing.JToolBar();
        button1 = new java.awt.Button();
        botonRegistrar = new java.awt.Button();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        BotonSalir = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, null, java.awt.Color.cyan, java.awt.Color.red));
        setToolTipText("<HTML>\n<h1>Modelo de Datos</h1>\n</HTML>");
        setName("PanelTrabajoPersonas"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 102, 102)));
        jPanel3.setToolTipText("");
        jPanel3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("DejaVu Serif Condensed", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 255));
        jLabel1.setText("- - - - - FORMULARIO DE  GESTIÓN DE USUARIOS - - - - -");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        form_Panel.setBackground(new java.awt.Color(204, 204, 204));
        form_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setText("DNI:");

        form_dni.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Apellidos:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Fech. Nacimiento: ");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("email: ");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("password: ");

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setRollover(true);

        button1.setBackground(new java.awt.Color(204, 153, 255));
        button1.setLabel("Cancelar");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jToolBar2.add(button1);
        button1.getAccessibleContext().setAccessibleName("LimpiarCampos");

        botonRegistrar.setBackground(new java.awt.Color(204, 153, 255));
        botonRegistrar.setLabel("Registrar ");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });
        jToolBar2.add(botonRegistrar);

        javax.swing.GroupLayout form_PanelLayout = new javax.swing.GroupLayout(form_Panel);
        form_Panel.setLayout(form_PanelLayout);
        form_PanelLayout.setHorizontalGroup(
            form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(form_PanelLayout.createSequentialGroup()
                        .addComponent(form_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(form_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(form_email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(form_ape1)
                    .addComponent(form_pwd, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(form_PanelLayout.createSequentialGroup()
                        .addComponent(form_ape2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(form_fechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        form_PanelLayout.setVerticalGroup(
            form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(form_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(form_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_ape1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(form_ape2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(form_fechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(form_PanelLayout.createSequentialGroup()
                        .addGroup(form_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(form_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(form_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(form_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(form_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(484, 484, 484)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setForeground(new java.awt.Color(153, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido1", "Apellido2", "FechaNAC", "email", "password"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("DNI");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Nombre");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Apellido1");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Apellido2");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("FechaNAC");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("email");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("password");
        }

        jToolBar1.setBackground(new java.awt.Color(204, 204, 204));
        jToolBar1.setRollover(true);

        BotonSalir.setText("Cerrar");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(BotonSalir);

        jTextField1.setText("!!ACLARACIÓN:¡¡  Para \"Eliminar\" y \"Buscar\" un Usuario. el valor se introduce por los campos de texto. Ejemplo: se escribe el apellido y pulsamos el boton\"Buscar\".");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("Si hay mas de una ocurrencia, mostrará tantas como haya dentro del listado. tanto en \"Buscar\" como en \"Eliminar\". Los ficheros se crean en la carpeta del proyecto");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2))))
                        .addGap(0, 204, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        jButton1.setBackground(new java.awt.Color(204, 153, 255));
        jButton1.setText("Buscar");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 153, 255));
        jButton2.setText("Imprimir TXT");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 153, 255));
        jButton3.setText("Imprimir JSON");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 153, 255));
        jButton4.setText("Eliminar");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 153, 255));
        jButton5.setText("Limpiar Campos");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 153, 255));
        jButton6.setText("Imprimir XML");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        //  Window w = SwingUtilities.getWindowAncestor(MiPanel.this);
        //   w.setVisible(false);
        this.setVisible(false);

    }//GEN-LAST:event_BotonSalirActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed

        Persona persona = new Persona();
        persona.setDni(form_dni.getText());
        persona.setNombre(form_nombre.getText());
        persona.setApellido1(form_ape1.getText());
        persona.setApellido2(form_ape2.getText());
        persona.setfechaNac(form_fechaNac.getText());
        persona.setEmail(form_email.getText());
        persona.setPassword(form_pwd.getText());
        String mensaje = "Se ha guardado el Usuario = ";
        JOptionPane.showMessageDialog(this, mensaje, "DATOS", JOptionPane.QUESTION_MESSAGE);
        if (!editando) {        // Si no esta editando creamos un nuevo usuario.
            modeloDatosPersona.setPersona(persona);
            listaPersonas2.add(persona);
            limpiarCampos();
        } else {    // Si esta editando modificamos el dato del modelo.
            modeloDatosPersona.setValueRow(persona, filaSeleccionada);
            limpiarCampos();
        }

    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        filaSeleccionada = this.jTable1.getSelectedRow();
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(this, "Debe selecionar alguna Fila", "error", JOptionPane.ERROR_MESSAGE);
        } else {
            editando = true;
            String mensaje = "Se dispone a editar la fila  " + filaSeleccionada;
            JOptionPane.showMessageDialog(this, mensaje, "DATOS", JOptionPane.INFORMATION_MESSAGE);
            form_Panel.setBackground(Color.GREEN);
            botonRegistrar.setLabel("Guardar");
            var persona = (Persona) this.listaPersonas.get(filaSeleccionada);
            cargarCampos(filaSeleccionada);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_button1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        /*---------------------BOTON PARA IMPRIMIR FICHERO TEXTO USUARIOS-------*/
        File f;
        FileWriter w;
        BufferedWriter bw;
        PrintWriter pw;

        try {
            f = new File("UsuariosTXT.txt");
            w = new FileWriter(f);
            bw = new BufferedWriter(w);
            pw = new PrintWriter(bw);
            Persona p2 = new Persona();

            for (int i = 0; i < listaPersonas2.size(); i++) {
                p2 = (Persona) listaPersonas2.get(i);
                pw.write(p2.getpersona());
            }

            pw.close();
            bw.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algo ha salido mal");
        }imprimirValor("El fichero de TEXTO se ha creado correctamente"); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*---------------------BOTON PARA BUSCAR UN USUARIO EN EL ARRAYLIST-------*/

        //- - -1º Declaramos variables- - -//
        ArrayList<Integer> Encontrados = new ArrayList<Integer>();
        Persona personabuscar = new Persona();
        String dni, nombre, ape1, ape2, fec, ema, pass;
        String busqueda = "";
        String atributo = "";
        int posicion = 0;

        /*- - -2º Comprobamos que el formulario no nos de un valor vacio- - -
         - - - -de lo contrario alamacenaremos nuestro valor de busqueda- - -*/
        dni = form_dni.getText();
        if (dni.isEmpty()) {
        } else {
            busqueda = dni;
            atributo = "dni";
        }
        nombre = form_nombre.getText();
        if (nombre.isEmpty()) {
        } else {
            busqueda = nombre;
            atributo = "nombre";
        }
        ape1 = form_ape1.getText();
        if (ape1.isEmpty()) {
        } else {
            busqueda = ape1;
            atributo = "apellido1";
        }
        ape2 = form_ape2.getText();
        if (ape2.isEmpty()) {
        } else {
            busqueda = ape2;
            atributo = "apellido2";
        }
        fec = form_fechaNac.getText();
        if (fec.isEmpty()) {
        } else {
            busqueda = fec;
            atributo = "fechaNac";
        }
        ema = form_email.getText();
        if (ema.isEmpty()) {
        } else {
            busqueda = ema;
            atributo = "email";
        }
        pass = form_pwd.getText();
        if (pass.isEmpty()) {
        } else {
            busqueda = pass;
            atributo = "password";
        }
        /*- - - 3º Buscamos las coincidencias de ese valor en nuestro Arraylist
             - - - y guardamos las apariciones en un Array de enteros - - -*/
        for (int i = 0; i < listaPersonas2.size(); i++) {
            personabuscar = (Persona) listaPersonas2.get(i);

            System.out.println(personabuscar.getDni());
            if (busqueda.equals(personabuscar.getDni())) {
                Encontrados.add(i);
            } else {
            }

            if (busqueda.equals(personabuscar.getNombre())) {
                Encontrados.add(i);
            } else {
            }

            if (busqueda.equals(personabuscar.getApellido1())) {
                Encontrados.add(i);
            } else {
            }

            if (busqueda.equals(personabuscar.getApellido2())) {
                Encontrados.add(i);
            } else {
            }

            if (busqueda.equals(personabuscar.getfechaNac())) {
                Encontrados.add(i);
            } else {
            }

            if (busqueda.equals(personabuscar.getEmail())) {
                Encontrados.add(i);
            } else {
            }

            if (busqueda.equals(personabuscar.getPassword())) {
                Encontrados.add(i);
            } else {
            }
        }

        for (int i = 0; i < Encontrados.size(); i++) {
            posicion = Encontrados.get(i);
            personabuscar = (Persona) listaPersonas2.get(posicion);

            imprimirValor("El usuario a buscar esta en la posicion: " + posicion + " y estos son sus datos "
                    + personabuscar.getpersona());
        }
        limpiarCampos();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

            for(int i=0;i<this.listaPersonas2.size();i++){
                FileWriter fileWriter = null;
                try {
                    var p = listaPersonas2.get(i);
                    Persona ps = (Persona) p;
                    JSONObject jsonObject = new JSONObject();
                    jsonObject.put("ID",ps.getDni());
                    jsonObject.put("Nombre",ps.getNombre());
                    jsonObject.put("Apellido1", ps.getApellido1());
                    jsonObject.put("Apellido2", ps.getApellido2());
                    jsonObject.put("Correo", ps.getEmail());
                    jsonObject.put("Año de nacimiento", ps.getfechaNac());
                    jsonObject.put("Contraseña", ps.getPassword());
                    jsonArray.add(jsonObject);
                    fileWriter = new FileWriter("UsuariosJSON.JSON");
                    fileWriter.write(jsonArray.toString());
                    fileWriter.flush();
                    fileWriter.close();
                } catch (IOException ex) {
                    Logger.getLogger(FormCapturaPersonas.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fileWriter.close();
                    } catch (IOException ex) {
                        Logger.getLogger(FormCapturaPersonas.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
      
            }    imprimirValor("El fichero de JSON se ha creado correctamente"); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        //--*-- FUNCION PARA ELIMINAR A UN USUARIO --*--//
        /*--1º DECLARAMOS VARIABLES--*/
        
        Persona personabuscar2 = new Persona();
        String dni, nombre, ape1, ape2, fec, ema, pass;
        String busqueda = "";
        int encontrado = 0;

        /*- - -2º Comprobamos que el formulario no nos de un valor vacio- - -
         - - - -de lo contrario alamacenaremos nuestro valor de busqueda- - -*/
        dni = form_dni.getText();
        if (dni.isEmpty()) {
        } else {
            busqueda = dni;
        }
        nombre = form_nombre.getText();
        if (nombre.isEmpty()) {
        } else {
            busqueda = nombre;

        }
        ape1 = form_ape1.getText();
        if (ape1.isEmpty()) {
        } else {
            busqueda = ape1;

        }
        ape2 = form_ape2.getText();
        if (ape2.isEmpty()) {
        } else {
            busqueda = ape2;

        }
        fec = form_fechaNac.getText();
        if (fec.isEmpty()) {
        } else {
            busqueda = fec;

        }
        ema = form_email.getText();
        if (ema.isEmpty()) {
        } else {
            busqueda = ema;

        }
        pass = form_pwd.getText();
        if (pass.isEmpty()) {
        } else {
            busqueda = pass;
        }

        /*- - - 3º Buscamos las coincidencias de ese valor en nuestro Arraylist
             - - - y guardamos las apariciones en un Array de enteros - - -*/
        for (int i = 0; i < listaPersonas2.size(); i++) {

            personabuscar2 = (Persona) listaPersonas2.get(i);

            System.out.println(personabuscar2.getDni());
            if (busqueda.equals(personabuscar2.getDni())) {
                encontrado = 1;
            } else {
            }

            if (busqueda.equals(personabuscar2.getNombre())) {
                encontrado = 1;
            } else {
            }

            if (busqueda.equals(personabuscar2.getApellido1())) {
                encontrado = 1;
            } else {
            }

            if (busqueda.equals(personabuscar2.getApellido2())) {
                encontrado = 1;
            } else {
            }

            if (busqueda.equals(personabuscar2.getfechaNac())) {
                encontrado = 1;
            } else {
            }

            if (busqueda.equals(personabuscar2.getPassword())) {
                encontrado = 1;
            } else {
            }

            if (encontrado == 1) {
                personabuscar2 = (Persona) listaPersonas.get(i);
                modeloDatosPersona.delPersona(i);
                listaPersonas2.remove(i);
            } else {
            }
            imprimirValor("El usuario a eliminar esta en la posicion: " + i + " y estos son sus datos "
                    + personabuscar2.getpersona());
            encontrado = 0;
        }
        System.out.println(busqueda);
        limpiarCampos();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //--*-- FUNCION PARA LIMPIAR LOS CUADROS DE TEXTO(CAMPOS) --*--//  
        limpiarCampos();
        imprimirValor("Los campos han sido limpiados");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        generador.generarDocumento(listaPersonas2);
        try {
            generador.generarXML();
        }catch (Exception ex) {
            Logger.getLogger(FormCapturaPersonas.class.getName()).log(Level.SEVERE, null, ex);
        }
        imprimirValor("El fichero de XML se ha creado correctamente"); 
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void limpiarCampos() {
        this.form_dni.setText("");
        this.form_nombre.setText("");
        this.form_ape1.setText("");
        this.form_ape2.setText("");
        this.form_fechaNac.setText("");
        this.form_email.setText("");
        this.form_pwd.setText("");
        if (editando) {
            form_Panel.setBackground(Color.LIGHT_GRAY);
            botonRegistrar.setLabel("Registrar");
            editando = false;
        }
    }

    private void cargarCampos(int filaSeleccionada) {

        var persona = (Persona) this.listaPersonas.get(filaSeleccionada);
        this.form_dni.setText(persona.getDni());
        this.form_nombre.setText(persona.getNombre());
        this.form_ape1.setText(persona.getApellido1());
        this.form_ape2.setText(persona.getApellido2());
        this.form_fechaNac.setText(persona.getfechaNac());
        this.form_email.setText(persona.getEmail());
        this.form_pwd.setText(persona.getPassword());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSalir;
    private java.awt.Button botonRegistrar;
    private java.awt.Button button1;
    private java.awt.Choice choice1;
    private javax.swing.JPanel form_Panel;
    private javax.swing.JTextField form_ape1;
    private javax.swing.JTextField form_ape2;
    private javax.swing.JTextField form_dni;
    private javax.swing.JTextField form_email;
    private javax.swing.JTextField form_fechaNac;
    private javax.swing.JTextField form_nombre;
    private javax.swing.JPasswordField form_pwd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
